USE AHR65_COPT
GO
SET NOCOUNT ON
GO
IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[ASYSUPDMOB]'))
DROP TABLE ASYSUPDMOB;
GO
CREATE TABLE [dbo].[ASYSUPDMOB](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CODICE] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABELLA] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPERAZIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATATRASF] [datetime] NULL,
	[CODICE_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAUPD] [datetime] NULL,
 CONSTRAINT [PK_ASYSUPDMOB] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ASYSUPDMOB_1] ON [dbo].[ASYSUPDMOB] 
(
	[DATAUPD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTI_V2]'))
DROP TRIGGER MODCONTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTI_V2]'))
DROP TRIGGER INSCONTI_V2;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODUTEWEB_V2]'))
DROP TRIGGER MODUTEWEB_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSUTEWEB_V2]'))
DROP TRIGGER INSUTEWEB_V2;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODAGENTI_V2]'))
DROP TRIGGER MODAGENTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSAGENTI_V2]'))
DROP TRIGGER INSAGENTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODARTICOLI_V2]'))
DROP TRIGGER MODARTICOLI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSARTICOLI_V2]'))
DROP TRIGGER INSARTICOLI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODKEYARTI_V2]'))
DROP TRIGGER MODKEYARTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSKEYARTI_V2]'))
DROP TRIGGER INSKEYARTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODPAGAMEN_V2]'))
DROP TRIGGER MODPAGAMEN_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSPAGAMEN_V2]'))
DROP TRIGGER INSPAGAMEN_V2;
GO
--
--LISTINIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINIM_V2]'))
DROP TRIGGER MODLISTINIM_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINIM_V2]'))
DROP TRIGGER INSLISTINIM_V2;
GO
--
--LISTINID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINID_V2]'))
DROP TRIGGER MODLISTINID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINID_V2]'))
DROP TRIGGER INSLISTINID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINID_V2]'))
DROP TRIGGER DELLISTINID_V2;
GO
--
--CONTRATTIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTIM_V2]'))
DROP TRIGGER MODCONTRATTIM_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTIM_V2]'))
DROP TRIGGER INSCONTRATTIM_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTIM_V2]'))
DROP TRIGGER DELCONTRATTIM_V2;
GO
--
--CONTRATTID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTID_V2]'))
DROP TRIGGER MODCONTRATTID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTID_V2]'))
DROP TRIGGER INSCONTRATTID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTID_V2]'))
DROP TRIGGER DELCONTRATTID_V2;
GO
--
--CONT_COSC
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONT_COSC_V2]'))
DROP TRIGGER MODCONT_COSC_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONT_COSC_V2]'))
DROP TRIGGER INSCONT_COSC_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONT_COSC_V2]'))
DROP TRIGGER DELCONT_COSC_V2;
GO

--
--CONT_COSC
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODSALDIART_V2]'))
DROP TRIGGER MODSALDIART_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSSALDIART_V2]'))
DROP TRIGGER INSSALDIART_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODGRUMERC_V2]'))
DROP TRIGGER MODGRUMERC_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSGRUMERC_V2]'))
DROP TRIGGER INSGRUMERC_V2;
GO

--DES_DIVE
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODDES_DIVE_V2]'))
DROP TRIGGER MODDES_DIVE_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSDES_DIVE_V2]'))
DROP TRIGGER INSDES_DIVE_V2;
GO

DECLARE @AZI CHAR(5)
DECLARE @SQL CHAR(2000)
        
SET @AZI='COPTG'

--MODCONTI_V2
SET @SQL='
	CREATE TRIGGER MODCONTI_V2 ON '+@AZI+'CONTI FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSCONTI_V2
SET @SQL='
	CREATE TRIGGER INSCONTI_V2 ON '+@AZI+'CONTI FOR INSERT 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--MODAGENTI_V2
SET @SQL='
CREATE TRIGGER MODAGENTI_V2 ON '+@AZI+'AGENTI FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSAGENTI_V2  
SET @SQL='
CREATE TRIGGER INSAGENTI_V2 ON '+@AZI+'AGENTI FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--MODARTICOLI_V2
SET @SQL='
	CREATE TRIGGER MODARTICOLI_V2 ON '+@AZI+'ART_ICOL FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSARTICOLI_V2
SET @SQL='
	CREATE TRIGGER INSARTICOLI_V2 ON '+@AZI+'ART_ICOL FOR INSERT 
	AS 
	  INSERT INTO ASYSUPDMOB 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--MODKEYARTI_V2
SET @SQL='
CREATE TRIGGER MODKEYARTI_V2 ON '+@AZI+'KEY_ARTI FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSKEYARTI_V2
SET @SQL='
CREATE TRIGGER INSKEYARTI_V2 ON '+@AZI+'KEY_ARTI FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--MODISTINIM
--
SET @SQL='
CREATE TRIGGER MODLISTINIM_V2 ON '+@AZI+'LISTINI FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSLISTINIM_V2
SET @SQL='
CREATE TRIGGER INSLISTINIM_V2 ON '+@AZI+'LISTINI FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--MODLISTINID_V2
--

SET @SQL='
CREATE TRIGGER MODLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT INSERTED.LICODART, ''LISTINI'', ''UPDATE'', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, DELETED.LICODART, DELETED.LIROWNUM, DELETED.LIQUANTI, GETDATE() FROM INSERTED, DELETED'
EXEC (@SQL)

--INSLISTINID_V2
SET @SQL='
CREATE TRIGGER INSLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LICODART, ''LISTINI'', ''UPDATE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--DELLISTINID_V2
SET @SQL='
CREATE TRIGGER DELLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LICODART, ''LISTINI'', ''DELETE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODCONTRATTIM_V2
--
SET @SQL='
CREATE TRIGGER MODCONTRATTIM_V2 ON '+@AZI+'CON_TRAM FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTIM_V2
SET @SQL='
CREATE TRIGGER INSCONTRATTIM_V2 ON '+@AZI+'CON_TRAM FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTIM_V2
SET @SQL='
CREATE TRIGGER DELCONTRATTIM_V2 ON '+@AZI+'CON_TRAM FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAM'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)

--
--MODCONTRATTID_V2
--
SET @SQL='
CREATE TRIGGER MODCONTRATTID_V2 ON '+@AZI+'CON_TRAD FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTID_V2
SET @SQL='
CREATE TRIGGER INSCONTRATTID_V2 ON '+@AZI+'CON_TRAD FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTID_V2
SET @SQL='
CREATE TRIGGER DELCONTRATTID_V2 ON '+@AZI+'CON_TRAD FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CONUMERO, ''CON_TRAD'', ''DELETE'', CPROWNUM, '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)

--
--MODCONT_COSC_V2
--
SET @SQL='
CREATE TRIGGER MODCONT_COSC_V2 ON '+@AZI+'CON_COSC FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT INSERTED.COCODICE, ''CONT_SCA'', ''UPDATE'', INSERTED.CONUMROW, INSERTED.COQUANTI, NULL, DELETED.COCODICE, DELETED.CONUMROW, DELETED.COQUANTI, GETDATE() FROM INSERTED, DELETED'
EXEC (@SQL)

--INSCONT_COSC_V2
SET @SQL='
CREATE TRIGGER INSCONT_COSC_V2 ON '+@AZI+'CON_COSC FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT COCODICE, ''CONT_SCA'', ''UPDATE'', CONUMROW, COQUANTI, NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--DELCONT_COSC_V2
SET @SQL='
CREATE TRIGGER DELCONT_COSC_V2 ON '+@AZI+'CON_COSC FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT COCODICE, ''CONT_SCA'', ''DELETE'', CONUMROW, COQUANTI, NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)

--
--MODSALDIART_V2
--
SET @SQL='
CREATE TRIGGER MODSALDIART_V2 ON '+@AZI+'SALDIART FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--INSSALDIART_V2
SET @SQL='
CREATE TRIGGER INSSALDIART_V2 ON '+@AZI+'SALDIART FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--MODGRUMERC_V2
SET @SQL='
CREATE TRIGGER MODGRUMERC_V2 ON '+@AZI+'GRUMERC FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--INSGRUMERC_V2
SET @SQL='
CREATE TRIGGER INSGRUMERC_V2 ON '+@AZI+'GRUMERC FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--MODDES_DIVE_V2
SET @SQL='
	CREATE TRIGGER MODDES_DIVE_V2 ON '+@AZI+'DES_DIVE FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSDES_DIVE_V2
SET @SQL='
CREATE TRIGGER INSDES_DIVE_V2 ON '+@AZI+'DES_DIVE FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--MODPAGAMEN_V2
SET @SQL='
	CREATE TRIGGER MODPAGAMEN_V2 ON '+@AZI+'PAG_AMEN FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT PACODICE, ''PAG_AMEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSPAGAMEN_V2
SET @SQL='
CREATE TRIGGER INSPAGAMEN_V2 ON '+@AZI+'PAG_AMEN FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT PACODICE, ''PAG_AMEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
