USE AHR65COPT
GO
SET NOCOUNT ON
GO
IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[AGGNEWSITE]'))
DROP TABLE AGGNEWSITE;
GO
CREATE TABLE [dbo].[AGGNEWSITE](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CODICE] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABELLA] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPERAZIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATATRASF] [datetime] NULL,
	[CODICE_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	
 CONSTRAINT [PK_AGGNEWSITE] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTI_NW]'))
DROP TRIGGER MODCONTI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTI_NW]'))
DROP TRIGGER INSCONTI_NW;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODUTEWEB_NW]'))
DROP TRIGGER MODUTEWEB_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSUTEWEB_NW]'))
DROP TRIGGER INSUTEWEB_NW;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODAGENTI_NW]'))
DROP TRIGGER MODAGENTI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSAGENTI_NW]'))
DROP TRIGGER INSAGENTI_NW;
GO
--
--ARTICOLI
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODARTICOLI_NW]'))
DROP TRIGGER MODARTICOLI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSARTICOLI_NW]'))
DROP TRIGGER INSARTICOLI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELARTICOLI_NW]'))
DROP TRIGGER DELARTICOLI_NW;
GO
--
--KEYARTI
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODKEYARTI_NW]'))
DROP TRIGGER MODKEYARTI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSKEYARTI_NW]'))
DROP TRIGGER INSKEYARTI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELKEYARTI_NW]'))
DROP TRIGGER DELKEYARTI_NW;
GO

--
--LISTINIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINIM_NW]'))
DROP TRIGGER MODLISTINIM_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINIM_NW]'))
DROP TRIGGER INSLISTINIM_NW;
GO
--
--LISTINID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINID_NW]'))
DROP TRIGGER MODLISTINID_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINID_NW]'))
DROP TRIGGER INSLISTINID_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINID_NW]'))
DROP TRIGGER DELLISTINID_NW;
GO
--
--CONTRATTIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTIM_NW]'))
DROP TRIGGER MODCONTRATTIM_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTIM_NW]'))
DROP TRIGGER INSCONTRATTIM_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTIM_NW]'))
DROP TRIGGER DELCONTRATTIM_NW;
GO
--
--CONTRATTID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTID_NW]'))
DROP TRIGGER MODCONTRATTID_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTID_NW]'))
DROP TRIGGER INSCONTRATTID_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTID_NW]'))
DROP TRIGGER DELCONTRATTID_NW;
GO
--
--CONT_COSC
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONT_COSC_NW]'))
DROP TRIGGER MODCONT_COSC_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONT_COSC_NW]'))
DROP TRIGGER INSCONT_COSC_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONT_COSC_NW]'))
DROP TRIGGER DELCONT_COSC_NW;
GO

--
--CONT_COSC
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODSALDIART_NW]'))
DROP TRIGGER MODSALDIART_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSSALDIART_NW]'))
DROP TRIGGER INSSALDIART_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODGRUMERC_NW]'))
DROP TRIGGER MODGRUMERC_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSGRUMERC_NW]'))
DROP TRIGGER INSGRUMERC_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODMARCHI_NW]'))
DROP TRIGGER MODMARCHI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSMARCHI_NW]'))
DROP TRIGGER INSMARCHI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODFAM_ARTI_NW]'))
DROP TRIGGER MODFAM_ARTI_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSFAM_ARTI_NW]'))
DROP TRIGGER INSFAM_ARTI_NW;
GO

--DES_DIVE
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODDES_DIVE_NW]'))
DROP TRIGGER MODDES_DIVE_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSDES_DIVE_NW]'))
DROP TRIGGER INSDES_DIVE_NW;
GO
--VOCIIVA
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODVOCIIVA_NW]'))
DROP TRIGGER MODVOCIIVA_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSVOCIIVA_NW]'))
DROP TRIGGER INSVOCIIVA_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELVOCIIVA_NW]'))
DROP TRIGGER DELVOCIIVA_NW;
GO
--PAG_AMEN
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODPAGAMEN_NW]'))
DROP TRIGGER MODPAGAMEN_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSPAGAMEN_NW]'))
DROP TRIGGER INSPAGAMEN_NW;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELPAGAMEN_NW]'))
DROP TRIGGER DELPAGAMEN_NW;
GO


DECLARE @AZI CHAR(5)
DECLARE @SQL CHAR(2000)
        
SET @AZI='COPTG'

--MODCONTI_NW
--SET @SQL='
--	CREATE TRIGGER MODCONTI_NW ON '+@AZI+'CONTI FOR UPDATE 
--	AS
--	  INSERT INTO AGGNEWSITE 
--	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
--EXEC (@SQL)
--INSCONTI_NW
--SET @SQL='
--CREATE TRIGGER INSCONTI_NW ON '+@AZI+'CONTI FOR INSERT 
--AS 
--  INSERT INTO AGGNEWSITE 
--  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
--EXEC (@SQL)
--
--
--MODUTEWEB_NW
SET @SQL='
	CREATE TRIGGER MODUTEWEB_NW ON '+@AZI+'ASYSUTEWEB FOR UPDATE 
	AS
	  INSERT INTO AGGNEWSITE 
	  SELECT UT_EMAIL, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSUTEWEB_NW
SET @SQL='
CREATE TRIGGER INSUTEWEB_NW ON '+@AZI+'ASYSUTEWEB FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT UT_EMAIL, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--
--MODAGENTI_NW
SET @SQL='
CREATE TRIGGER MODAGENTI_NW ON '+@AZI+'AGENTI FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSAGENTI_NW  
SET @SQL='
CREATE TRIGGER INSAGENTI_NW ON '+@AZI+'AGENTI FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODARTICOLI_NW
SET @SQL='
	CREATE TRIGGER MODARTICOLI_NW ON '+@AZI+'ART_ICOL FOR UPDATE 
	AS
	  INSERT INTO AGGNEWSITE 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSARTICOLI_NW
SET @SQL='
	CREATE TRIGGER INSARTICOLI_NW ON '+@AZI+'ART_ICOL FOR INSERT 
	AS 
	  INSERT INTO AGGNEWSITE 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--DELARTICOLI_NW
--
SET @SQL='
CREATE TRIGGER DELARTICOLI_NW ON '+@AZI+'ART_ICOL FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT ARCODART, ''ARTICOLI'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)
--
--MODKEYARTI_NW
--
SET @SQL='
CREATE TRIGGER MODKEYARTI_NW ON '+@AZI+'KEY_ARTI FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSKEYARTI_NW
SET @SQL='
CREATE TRIGGER INSKEYARTI_NW ON '+@AZI+'KEY_ARTI FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--DELKEYARTI_NW
--
SET @SQL='
CREATE TRIGGER DELKEYARTI_NW ON '+@AZI+'KEY_ARTI FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CACODICE, ''KEYARTI'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)
--
--MODISTINIM
--
SET @SQL='
CREATE TRIGGER MODLISTINIM_NW ON '+@AZI+'LISTINI FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSLISTINIM_NW
SET @SQL='
CREATE TRIGGER INSLISTINIM_NW ON '+@AZI+'LISTINI FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--MODLISTINID_NW
--

SET @SQL='
CREATE TRIGGER MODLISTINID_NW ON '+@AZI+'LIS_SCAG FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT INSERTED.LICODART, ''LISTINI'', ''UPDATE'', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, DELETED.LICODART, DELETED.LIROWNUM, DELETED.LIQUANTI FROM INSERTED, DELETED'
EXEC (@SQL)

--INSLISTINID_NW
SET @SQL='
CREATE TRIGGER INSLISTINID_NW ON '+@AZI+'LIS_SCAG FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT LICODART, ''LISTINI'', ''UPDATE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELLISTINID_NW
SET @SQL='
CREATE TRIGGER DELLISTINID_NW ON '+@AZI+'LIS_SCAG FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT LICODART, ''LISTINI'', ''DELETE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)
--
--MODCONTRATTIM_NW
--
SET @SQL='
CREATE TRIGGER MODCONTRATTIM_NW ON '+@AZI+'CON_TRAM FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTIM_NW
SET @SQL='
CREATE TRIGGER INSCONTRATTIM_NW ON '+@AZI+'CON_TRAM FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTIM_NW
SET @SQL='
CREATE TRIGGER DELCONTRATTIM_NW ON '+@AZI+'CON_TRAM FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAM'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODCONTRATTID_NW
--
SET @SQL='
CREATE TRIGGER MODCONTRATTID_NW ON '+@AZI+'CON_TRAD FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTID_NW
SET @SQL='
CREATE TRIGGER INSCONTRATTID_NW ON '+@AZI+'CON_TRAD FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTID_NW
SET @SQL='
CREATE TRIGGER DELCONTRATTID_NW ON '+@AZI+'CON_TRAD FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT CONUMERO, ''CON_TRAD'', ''DELETE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODCONT_COSC_NW
--
SET @SQL='
CREATE TRIGGER MODCONT_COSC_NW ON '+@AZI+'CON_COSC FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT INSERTED.COCODICE, ''CONT_SCA'', ''UPDATE'', INSERTED.CONUMROW, INSERTED.COQUANTI, NULL, DELETED.COCODICE, DELETED.CONUMROW, DELETED.COQUANTI FROM INSERTED, DELETED'
EXEC (@SQL)

--INSCONT_COSC_NW
SET @SQL='
CREATE TRIGGER INSCONT_COSC_NW ON '+@AZI+'CON_COSC FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT COCODICE, ''CONT_SCA'', ''UPDATE'', CONUMROW, COQUANTI, NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONT_COSC_NW
SET @SQL='
CREATE TRIGGER DELCONT_COSC_NW ON '+@AZI+'CON_COSC FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT COCODICE, ''CONT_SCA'', ''DELETE'', CONUMROW, COQUANTI, NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODSALDIART_NW
--
SET @SQL='
CREATE TRIGGER MODSALDIART_NW ON '+@AZI+'SALDIART FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSSALDIART_NW
SET @SQL='
CREATE TRIGGER INSSALDIART_NW ON '+@AZI+'SALDIART FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODGRUMERC_NW
SET @SQL='
CREATE TRIGGER MODGRUMERC_NW ON '+@AZI+'GRUMERC FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSGRUMERC_NW
SET @SQL='
CREATE TRIGGER INSGRUMERC_NW ON '+@AZI+'GRUMERC FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODMARCHI_NW
SET @SQL='
CREATE TRIGGER MODMARCHI_NW ON '+@AZI+'MARCHI FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT MACODICE, ''MARCHI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSMARCHI_NW
SET @SQL='
CREATE TRIGGER INSMARCHI_NW ON '+@AZI+'MARCHI FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT MACODICE, ''MARCHI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODFAM_ARTI_NW
SET @SQL='
CREATE TRIGGER MODFAM_ARTI_NW ON '+@AZI+'FAM_ARTI FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT FACODICE, ''FAM_ARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSFAM_ARTI_NW
SET @SQL='
CREATE TRIGGER INSFAM_ARTI_NW ON '+@AZI+'FAM_ARTI FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT FACODICE, ''FAM_ARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)


--MODDES_DIVE_NW
SET @SQL='
	CREATE TRIGGER MODDES_DIVE_NW ON '+@AZI+'DES_DIVE FOR UPDATE 
	AS
	  INSERT INTO AGGNEWSITE 
	  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSDES_DIVE_NW
SET @SQL='
CREATE TRIGGER INSDES_DIVE_NW ON '+@AZI+'DES_DIVE FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODVOCIIVA_NW
SET @SQL='
CREATE TRIGGER MODVOCIIVA_NW ON '+@AZI+'VOCIIVA FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT IVCODIVA, ''VOCIIVA'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSVOCIIVA_NW
SET @SQL='
CREATE TRIGGER INSVOCIIVA_NW ON '+@AZI+'VOCIIVA FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT IVCODIVA, ''VOCIIVA'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--DELVOCIIVA_NW
SET @SQL='
CREATE TRIGGER DELVOCIIVA_NW ON '+@AZI+'VOCIIVA FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT IVCODIVA, ''VOCIIVA'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--MODPAGAMEN_NW
SET @SQL='
CREATE TRIGGER MODPAGAMEN_NW ON '+@AZI+'PAG_AMEN FOR UPDATE 
AS
  INSERT INTO AGGNEWSITE 
  SELECT PACODICE, ''PAGAMEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSPAGAMEN_NW
SET @SQL='
CREATE TRIGGER INSPAGAMEN_NW ON '+@AZI+'PAG_AMEN FOR INSERT 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT PACODICE, ''PAGAMEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--DELPAGAMEN_NW
SET @SQL='
CREATE TRIGGER DELPAGAMEN_NW ON '+@AZI+'PAG_AMEN FOR DELETE 
AS 
  INSERT INTO AGGNEWSITE 
  SELECT PACODICE, ''PAGAMEN'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)