USE AHR65_COPT
GO
IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[AGGIORNAMENTI]'))
DROP TABLE AGGIORNAMENTI;
GO
DECLARE @AZI CHAR(5),
        @SQL CHAR(200)
SET @AZI='COPTG'
CREATE TABLE [dbo].[AGGIORNAMENTI](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CODICE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABELLA] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPERAZIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATATRASF] [datetime] NULL,
	[CODICE_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	
 CONSTRAINT [PK_AGGIORNAMENTI] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTI]'))
DROP TRIGGER MODCONTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTI]'))
DROP TRIGGER INSCONTI;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODAGENTI]'))
DROP TRIGGER MODAGENTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSAGENTI]'))
DROP TRIGGER INSAGENTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODARTICOLI]'))
DROP TRIGGER MODARTICOLI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSARTICOLI]'))
DROP TRIGGER INSARTICOLI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODKEYARTI]'))
DROP TRIGGER MODKEYARTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSKEYARTI]'))
DROP TRIGGER INSKEYARTI;
GO
--
--LISTINIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINIM]'))
DROP TRIGGER MODLISTINIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINIM]'))
DROP TRIGGER INSLISTINIM;
GO
--
--LISTINID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINID]'))
DROP TRIGGER MODLISTINID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINID]'))
DROP TRIGGER INSLISTINID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINID]'))
DROP TRIGGER DELLISTINID;
GO
--
--CONTRATTIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTIM]'))
DROP TRIGGER MODCONTRATTIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTIM]'))
DROP TRIGGER INSCONTRATTIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTIM]'))
DROP TRIGGER DELCONTRATTIM;
GO
--
--CONTRATTID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTID]'))
DROP TRIGGER MODCONTRATTID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTID]'))
DROP TRIGGER INSCONTRATTID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTID]'))
DROP TRIGGER DELCONTRATTID;
GO
--
--CONT_COSC
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONT_COSC]'))
DROP TRIGGER MODCONT_COSC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONT_COSC]'))
DROP TRIGGER INSCONT_COSC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONT_COSC]'))
DROP TRIGGER DELCONT_COSC;
GO
--
--CONT_COSC

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODSALDIART]'))
DROP TRIGGER MODSALDIART;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSSALDIART]'))
DROP TRIGGER INSSALDIART;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODGRUMERC]'))
DROP TRIGGER MODGRUMERC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSGRUMERC]'))
DROP TRIGGER INSGRUMERC;
GO

SET @SQL='
	CREATE TRIGGER MODCONTI ON '+@AZI+'CONTI FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT ANCODICE, '''CLIENTI''', '''UPDATE''', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

CREATE TRIGGER INSCONTI ON COPTGCONTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT ANCODICE, 'CLIENTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO

CREATE TRIGGER MODAGENTI ON COPTGAGENTI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT AGCODAGE, 'AGENTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSAGENTI ON COPTGAGENTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT AGCODAGE, 'AGENTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO

CREATE TRIGGER MODARTICOLI ON COPTGART_ICOL FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT ARCODART, 'ARTICOLI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSARTICOLI ON COPTGART_ICOL FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT ARCODART, 'ARTICOLI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO

CREATE TRIGGER MODKEYARTI ON COPTGKEY_ARTI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CACODICE, 'KEYARTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSKEYARTI ON COPTGKEY_ARTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CACODICE, 'KEYARTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
--
--LISTINIM
--
CREATE TRIGGER MODLISTINIM ON COPTGLISTINI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT LSCODLIS, 'LISTINIM', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSLISTINIM ON COPTGLISTINI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT LSCODLIS, 'LISTINIM', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
--
--LISTINID
--
CREATE TRIGGER MODLISTINID ON COPTGLIS_SCAG FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT INSERTED.LICODART, 'LISTINI', 'UPDATE', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, DELETED.LICODART, DELETED.LIROWNUM, DELETED.LIQUANTI FROM INSERTED, DELETED;
GO
CREATE TRIGGER INSLISTINID ON COPTGLIS_SCAG FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT INSERTED.LICODART, 'LISTINI', 'UPDATE', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, '', '', '' FROM INSERTED, DELETED;
GO
CREATE TRIGGER DELLISTINID ON COPTGLIS_SCAG FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT LICODART, 'LISTINI', 'DELETE', LIROWNUM, LIQUANTI, NULL, '', '', '' FROM DELETED;
GO
--
--CONTRATTIM
--
CREATE TRIGGER MODCONTRATTIM ON COPTGCON_TRAM FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSCONTRATTIM ON COPTGCON_TRAM FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER DELCONTRATTIM ON COPTGCON_TRAM FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'DELETE', '', '', NULL, '', '', '' FROM DELETED;
GO
--
--CONTRATTID
--
CREATE TRIGGER MODCONTRATTID ON COPTGCON_TRAD FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'UPDATE', CPROWNUM, '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSCONTRATTID ON COPTGCON_TRAD FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'UPDATE', CPROWNUM, '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER DELCONTRATTID ON COPTGCON_TRAD FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, 'CONTRATTI', 'DELETE', CPROWNUM, '', NULL, '', '', '' FROM DELETED;
GO
--
--CONT_COSC
--
CREATE TRIGGER MODCONT_COSC ON COPTGCON_COSC FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT INSERTED.COCODICE, 'CONT_SCA', 'UPDATE', INSERTED.CONUMROW, INSERTED.COQUANTI, NULL, DELETED.COCODICE, DELETED.CONUMROW, DELETED.COQUANTI FROM INSERTED, DELETED;
GO
CREATE TRIGGER INSCONT_COSC ON COPTGCON_COSC FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT COCODICE, 'CONT_SCA', 'UPDATE', CONUMROW, COQUANTI, NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER DELCONT_COSC ON COPTGCON_COSC FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT COCODICE, 'CONT_SCA', 'DELETE', CONUMROW, COQUANTI, NULL, '', '', '' FROM DELETED;
GO
--
--SALDIART
--
CREATE TRIGGER MODSALDIART ON COPTGSALDIART FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT SLCODICE, 'SALDIART', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSSALDIART ON COPTGSALDIART FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT SLCODICE, 'SALDIART', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO

CREATE TRIGGER MODGRUMERC ON COPTGGRUMERC FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT GMCODICE, 'GRUMERC', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
CREATE TRIGGER INSGRUMERC ON COPTGGRUMERC FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT GMCODICE, 'GRUMERC', 'UPDATE', '', '', NULL, '', '', '' FROM INSERTED;
GO
