USE AHR_ALTRAQ
GO
SET NOCOUNT ON
GO
IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[AGGIORNAMENTI]'))
DROP TABLE AGGIORNAMENTI;
GO
CREATE TABLE [dbo].[AGGIORNAMENTI](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CODICE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABELLA] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPERAZIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATATRASF] [datetime] NULL,
	[CODICE_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	
 CONSTRAINT [PK_AGGIORNAMENTI] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTI]'))
DROP TRIGGER MODCONTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTI]'))
DROP TRIGGER INSCONTI;
GO

IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODAGENTI]'))
DROP TRIGGER MODAGENTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSAGENTI]'))
DROP TRIGGER INSAGENTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODARTICOLI]'))
DROP TRIGGER MODARTICOLI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSARTICOLI]'))
DROP TRIGGER INSARTICOLI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODKEYARTI]'))
DROP TRIGGER MODKEYARTI;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSKEYARTI]'))
DROP TRIGGER INSKEYARTI;
GO
--
--LISTINIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINIM]'))
DROP TRIGGER MODLISTINIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINIM]'))
DROP TRIGGER INSLISTINIM;
GO
--
--LISTINID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINID]'))
DROP TRIGGER MODLISTINID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINID]'))
DROP TRIGGER INSLISTINID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINID]'))
DROP TRIGGER DELLISTINID;
GO
--
--CONTRATTIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTIM]'))
DROP TRIGGER MODCONTRATTIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTIM]'))
DROP TRIGGER INSCONTRATTIM;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTIM]'))
DROP TRIGGER DELCONTRATTIM;
GO
--
--CONTRATTID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTRATTID]'))
DROP TRIGGER MODCONTRATTID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTRATTID]'))
DROP TRIGGER INSCONTRATTID;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTRATTID]'))
DROP TRIGGER DELCONTRATTID;
GO
--
--CONT_COSC
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONT_COSC]'))
DROP TRIGGER MODCONT_COSC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONT_COSC]'))
DROP TRIGGER INSCONT_COSC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONT_COSC]'))
DROP TRIGGER DELCONT_COSC;
GO

--
--CONT_COSC
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODSALDIART]'))
DROP TRIGGER MODSALDIART;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSSALDIART]'))
DROP TRIGGER INSSALDIART;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODGRUMERC]'))
DROP TRIGGER MODGRUMERC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSGRUMERC]'))
DROP TRIGGER INSGRUMERC;
GO

--DES_DIVE
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODDES_DIVE]'))
DROP TRIGGER MODDES_DIVE;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSDES_DIVE]'))
DROP TRIGGER INSDES_DIVE;
GO
--CATEGOA
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCATEGOA]'))
DROP TRIGGER MODCATEGOA;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCATEGOA]'))
DROP TRIGGER INSCATEGOA;
GO
--CATEGOB
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCATEGOB]'))
DROP TRIGGER MODCATEGOB;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCATEGOB]'))
DROP TRIGGER INSCATEGOB;
GO
--CATEGOC
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCATEGOC]'))
DROP TRIGGER MODCATEGOC;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCATEGOC]'))
DROP TRIGGER INSCATEGOC;
GO


DECLARE @AZI CHAR(5)
DECLARE @SQL CHAR(2000)
        
SET @AZI='ALTRQ'

--MODCONTI
SET @SQL='
	CREATE TRIGGER MODCONTI ON '+@AZI+'CONTI FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSCONTI
SET @SQL='
CREATE TRIGGER INSCONTI ON '+@AZI+'CONTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODAGENTI
SET @SQL='
CREATE TRIGGER MODAGENTI ON '+@AZI+'AGENTI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSAGENTI  
SET @SQL='
CREATE TRIGGER INSAGENTI ON '+@AZI+'AGENTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT AGCODAGE, ''AGENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODARTICOLI
SET @SQL='
	CREATE TRIGGER MODARTICOLI ON '+@AZI+'ART_ICOL FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSARTICOLI
SET @SQL='
	CREATE TRIGGER INSARTICOLI ON '+@AZI+'ART_ICOL FOR INSERT 
	AS 
	  INSERT INTO AGGIORNAMENTI 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODKEYARTI
SET @SQL='
CREATE TRIGGER MODKEYARTI ON '+@AZI+'KEY_ARTI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSKEYARTI
SET @SQL='
CREATE TRIGGER INSKEYARTI ON '+@AZI+'KEY_ARTI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--MODISTINIM
--
SET @SQL='
CREATE TRIGGER MODLISTINIM ON '+@AZI+'LISTINI FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSLISTINIM
SET @SQL='
CREATE TRIGGER INSLISTINIM ON '+@AZI+'LISTINI FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--
--MODLISTINID
--

SET @SQL='
CREATE TRIGGER MODLISTINID ON '+@AZI+'LIS_SCAG FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT INSERTED.LICODART, ''LISTINI'', ''UPDATE'', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, DELETED.LICODART, DELETED.LIROWNUM, DELETED.LIQUANTI FROM INSERTED, DELETED'
EXEC (@SQL)

--INSLISTINID
SET @SQL='
CREATE TRIGGER INSLISTINID ON '+@AZI+'LIS_SCAG FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT LICODART, ''LISTINI'', ''UPDATE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELLISTINID
SET @SQL='
CREATE TRIGGER DELLISTINID ON '+@AZI+'LIS_SCAG FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT LICODART, ''LISTINI'', ''DELETE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)
--
--MODCONTRATTIM
--
SET @SQL='
CREATE TRIGGER MODCONTRATTIM ON '+@AZI+'CON_TRAM FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTIM
SET @SQL='
CREATE TRIGGER INSCONTRATTIM ON '+@AZI+'CON_TRAM FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTIM
SET @SQL='
CREATE TRIGGER DELCONTRATTIM ON '+@AZI+'CON_TRAM FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAM'', ''DELETE'', '''', '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODCONTRATTID
--
SET @SQL='
CREATE TRIGGER MODCONTRATTID ON '+@AZI+'CON_TRAD FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSCONTRATTID
SET @SQL='
CREATE TRIGGER INSCONTRATTID ON '+@AZI+'CON_TRAD FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAD'', ''UPDATE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONTRATTID
SET @SQL='
CREATE TRIGGER DELCONTRATTID ON '+@AZI+'CON_TRAD FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CONUMERO, ''CON_TRAD'', ''DELETE'', CPROWNUM, '''', NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODCONT_COSC
--
SET @SQL='
CREATE TRIGGER MODCONT_COSC ON '+@AZI+'CON_COSC FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT INSERTED.COCODICE, ''CONT_SCA'', ''UPDATE'', INSERTED.CONUMROW, INSERTED.COQUANTI, NULL, DELETED.COCODICE, DELETED.CONUMROW, DELETED.COQUANTI FROM INSERTED, DELETED'
EXEC (@SQL)

--INSCONT_COSC
SET @SQL='
CREATE TRIGGER INSCONT_COSC ON '+@AZI+'CON_COSC FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT COCODICE, ''CONT_SCA'', ''UPDATE'', CONUMROW, COQUANTI, NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--DELCONT_COSC
SET @SQL='
CREATE TRIGGER DELCONT_COSC ON '+@AZI+'CON_COSC FOR DELETE 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT COCODICE, ''CONT_SCA'', ''DELETE'', CONUMROW, COQUANTI, NULL, '''', '''', '''' FROM DELETED'
EXEC (@SQL)

--
--MODSALDIART
--
SET @SQL='
CREATE TRIGGER MODSALDIART ON '+@AZI+'SALDIART FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSSALDIART
SET @SQL='
CREATE TRIGGER INSSALDIART ON '+@AZI+'SALDIART FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODGRUMERC
SET @SQL='
CREATE TRIGGER MODGRUMERC ON '+@AZI+'GRUMERC FOR UPDATE 
AS
  INSERT INTO AGGIORNAMENTI 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--INSGRUMERC
SET @SQL='
CREATE TRIGGER INSGRUMERC ON '+@AZI+'GRUMERC FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT GMCODICE, ''GRUMERC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)

--MODDES_DIVE
SET @SQL='
	CREATE TRIGGER MODDES_DIVE ON '+@AZI+'DES_DIVE FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSDES_DIVE
SET @SQL='
CREATE TRIGGER INSDES_DIVE ON '+@AZI+'DES_DIVE FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT DDCODICE, ''DES_DIVE'', ''UPDATE'', DDCODDES, '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODCATEGOA
SET @SQL='
	CREATE TRIGGER MODCATEGOA ON '+@AZI+'CATEGOA FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT CTCODICE, ''CATEGOA'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSCATEGOA
SET @SQL='
CREATE TRIGGER INSCATEGOA ON '+@AZI+'CATEGOA FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CTCODICE, ''CATEGOA'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODCATEGOB
SET @SQL='
	CREATE TRIGGER MODCATEGOB ON '+@AZI+'CATEGOB FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT CTCODICE, ''CATEGOB'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSCATEGOB
SET @SQL='
CREATE TRIGGER INSCATEGOB ON '+@AZI+'CATEGOB FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CTCODICE, ''CATEGOB'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--MODCATEGOC
SET @SQL='
	CREATE TRIGGER MODCATEGOC ON '+@AZI+'CATEGOC FOR UPDATE 
	AS
	  INSERT INTO AGGIORNAMENTI 
	  SELECT CTCODICE, ''CATEGOC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
--INSCATEGOC
SET @SQL='
CREATE TRIGGER INSCATEGOC ON '+@AZI+'CATEGOC FOR INSERT 
AS 
  INSERT INTO AGGIORNAMENTI 
  SELECT CTCODICE, ''CATEGOC'', ''UPDATE'', '''', '''', NULL, '''', '''', '''' FROM INSERTED'
EXEC (@SQL)
