USE AHR65COPT
GO
SET NOCOUNT ON
GO
IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[ASYSUPDMOB]'))
DROP TABLE ASYSUPDMOB;
GO
CREATE TABLE [dbo].[ASYSUPDMOB](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[CODICE] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABELLA] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OPERAZIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATATRASF] [datetime] NULL,
	[CODICE_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODSEC_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODTER_O] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAUPD] [datetime] NULL,
 CONSTRAINT [PK_ASYSUPDMOB] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ASYSUPDMOB_1] ON [dbo].[ASYSUPDMOB] 
(
	[DATAUPD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]


IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[ASYSVENDORLOG]'))
DROP TABLE ASYSVENDORLOG;
GO
CREATE TABLE [dbo].[ASYSVENDORLOG](
	[NUMREC] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[AZIENDA] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGENTE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAUPD] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERSIONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REMOTEFOLDER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOCALFOLDER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORDERFOLDER] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
 CONSTRAINT [PK_ASYSVENDORLOG] PRIMARY KEY CLUSTERED 
(
	[NUMREC] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ASYSVENDORLOG_1] ON [dbo].[ASYSVENDORLOG] 
(
	[DATAUPD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]


IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODCONTI_V2]'))
DROP TRIGGER MODCONTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSCONTI_V2]'))
DROP TRIGGER INSCONTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELCONTI_V2]'))
DROP TRIGGER DELCONTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODARTICOLI_V2]'))
DROP TRIGGER MODARTICOLI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSARTICOLI_V2]'))
DROP TRIGGER INSARTICOLI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELARTICOLI_V2]'))
DROP TRIGGER DELARTICOLI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODKEYARTI_V2]'))
DROP TRIGGER MODKEYARTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSKEYARTI_V2]'))
DROP TRIGGER INSKEYARTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELKEYARTI_V2]'))
DROP TRIGGER DELKEYARTI_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODUBICAZ_V2]'))
DROP TRIGGER MODUBICAZ_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSUBICAZ_V2]'))
DROP TRIGGER INSUBICAZ_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELUBICAZ_V2]'))
DROP TRIGGER DELUBICAZ_V2;
GO
--
--LISTINIM
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINIM_V2]'))
DROP TRIGGER MODLISTINIM_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINIM_V2]'))
DROP TRIGGER INSLISTINIM_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINIM_V2]'))
DROP TRIGGER DELLISTINIM_V2;
GO
--
--LISTINID
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODLISTINID_V2]'))
DROP TRIGGER MODLISTINID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSLISTINID_V2]'))
DROP TRIGGER INSLISTINID_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[DELLISTINID_V2]'))
DROP TRIGGER DELLISTINID_V2;
GO
--
--SALDIART
--
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[MODSALDIART_V2]'))
DROP TRIGGER MODSALDIART_V2;
GO
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[INSSALDIART_V2]'))
DROP TRIGGER INSSALDIART_V2;
GO
--
--



DECLARE @AZI CHAR(5)
DECLARE @SQL CHAR(2000)
        
SET @AZI='COPTG'
--MODCONTI_V2
SET @SQL='
	CREATE TRIGGER MODCONTI_V2 ON '+@AZI+'CONTI FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--INSCONTI_V2
SET @SQL='
	CREATE TRIGGER INSCONTI_V2 ON '+@AZI+'CONTI FOR INSERT 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ANCODICE, ''CLIENTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--DELCONTI_V2
SET @SQL='
	CREATE TRIGGER DELCONTI_V2 ON '+@AZI+'CONTI FOR DELETE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ANCODICE, ''CLIENTI'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODARTICOLI_V2
--
SET @SQL='
	CREATE TRIGGER MODARTICOLI_V2 ON '+@AZI+'ART_ICOL FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--INSARTICOLI_V2
--
SET @SQL='
	CREATE TRIGGER INSARTICOLI_V2 ON '+@AZI+'ART_ICOL FOR INSERT 
	AS 
	  INSERT INTO ASYSUPDMOB 
	  SELECT ARCODART, ''ARTICOLI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--DELARTICOLI_V2
--
SET @SQL='
CREATE TRIGGER DELARTICOLI_V2 ON '+@AZI+'ART_ICOL FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT ARCODART, ''ARTICOLI'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODKEYARTI_V2
--
SET @SQL='
CREATE TRIGGER MODKEYARTI_V2 ON '+@AZI+'KEY_ARTI FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--INSKEYARTI_V2
--
SET @SQL='
CREATE TRIGGER INSKEYARTI_V2 ON '+@AZI+'KEY_ARTI FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CACODICE, ''KEYARTI'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--DELKEYARTI_V2
--
SET @SQL='
CREATE TRIGGER DELKEYARTI_V2 ON '+@AZI+'KEY_ARTI FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT CACODICE, ''KEYARTI'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODUBICAZ_V2
--
SET @SQL='
	CREATE TRIGGER MODUBICAZ_V2 ON '+@AZI+'UBICAZIONI FOR UPDATE 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT UBCODART, ''LOTTOVEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--INSUBICAZ_V2
--
SET @SQL='
	CREATE TRIGGER INSUBICAZ_V2 ON '+@AZI+'UBICAZIONI FOR INSERT 
	AS
	  INSERT INTO ASYSUPDMOB 
	  SELECT UBCODART, ''LOTTOVEN'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--DELLUBICAZ_V2
--
SET @SQL='
CREATE TRIGGER DELUBICAZ_V2 ON '+@AZI+'UBICAZIONI FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT UBCODART, ''LOTTOVEN'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODISTINIM_V2
--
SET @SQL='
CREATE TRIGGER MODLISTINIM_V2 ON '+@AZI+'LISTINI FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--INSLISTINIM_V2
--
SET @SQL='
CREATE TRIGGER INSLISTINIM_V2 ON '+@AZI+'LISTINI FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LSCODLIS, ''LISTINIM'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--DELLLISTINIM_V2
--
SET @SQL='
CREATE TRIGGER DELLISTINIM_V2 ON '+@AZI+'LISTINI FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LSCODLIS, ''LISTINIM'', ''DELETE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODLISTINID_V2
--
SET @SQL='
CREATE TRIGGER MODLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT DELETED.LICODART, ''LISTINI'', ''DELETE'', DELETED.LIROWNUM, DELETED.LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM DELETED
  INSERT INTO ASYSUPDMOB 
  SELECT INSERTED.LICODART, ''LISTINI'', ''UPDATE'', INSERTED.LIROWNUM, INSERTED.LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--INSLISTINID_V2
--
SET @SQL='
CREATE TRIGGER INSLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LICODART, ''LISTINI'', ''UPDATE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
--
--DELLISTINID_V2
--
SET @SQL='
CREATE TRIGGER DELLISTINID_V2 ON '+@AZI+'LIS_SCAG FOR DELETE 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT LICODART, ''LISTINI'', ''DELETE'', LIROWNUM, LIQUANTI, NULL, '''', '''', '''', GETDATE() FROM DELETED'
EXEC (@SQL)
--
--MODSALDIART_V2
--
SET @SQL='
CREATE TRIGGER MODSALDIART_V2 ON '+@AZI+'SALDIART FOR UPDATE 
AS
  INSERT INTO ASYSUPDMOB 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)

--INSSALDIART_V2
SET @SQL='
CREATE TRIGGER INSSALDIART_V2 ON '+@AZI+'SALDIART FOR INSERT 
AS 
  INSERT INTO ASYSUPDMOB 
  SELECT SLCODICE, ''SALDIART'', ''UPDATE'', '''', '''', NULL, '''', '''', '''', GETDATE() FROM INSERTED'
EXEC (@SQL)
